export const Colors = {
  primary: "#6DABB6",
  primaryShade: "#6E9CE0",
  primaryShadeNotActive: "#486083",
  primaryTint: "#B7CCEC",
  primaryTintLighter: "#DEE7F4",
  primaryLight: "#f8fafc",
  primaryDark: "#2F3537",
  // primaryDark: "#283132",
  primaryDarkLighter: "#525E60",
  primaryDarkEvenLighter: "#CDD5D6",
  amber: "#fde68a",
  red: "#f87171",
  redDark: "#443333",
  gradientBlue: "#6E9CE0",
  gradientBlueLight: "#9ABEF4",
  //0///////////////////////////////////////////////
  // primaryShade: "#6E9CE0",
  // primaryTint: "#B7CCEC",
  // primaryTintLighter: "#DEE7F4",
  // primaryLight: "#f8fafc",
  // primaryDark: "#283132",
  // primaryDarkLighter: "#525E60",
  // primaryDarkEvenLighter: "#CDD5D6",
  // amber: "#FED9B7",
  // red: "#f87171",
  // redLight: "#FFEFEF",
  // gradientBlue: "#6E9CE0",
  // gradientBlueLight: "#9ABEF4",
  // secondaryLight: "#fca5a5",
  //0///////////////////////////////////////////////
  // primaryShade: "#6E9CE0",
  // primaryTint: "#B7CCEC",
  // primaryTintLighter: "#DEE7F4",
  // primaryLight: "#f8fafc",
  // primaryDark: "#283132",
  // primaryDarkLighter: "#525E60",
  // primaryDarkEvenLighter: "#CDD5D6",
  // amber: "#FED9B7",
  // red: "#f87171",
  // redLight: "#FFEFEF",
  // gradientBlue: "#6E9CE0",
  // gradientBlueLight: "#9ABEF4",
  // secondaryLight: "#fca5a5",
};
